name: Build CapibaraZero firmware

on: [push]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Prepare PN532 libraries
        run: bash init_nfc_libs.sh
      - name: Prepare release folder
        run: mkdir release
      - name: Build ESP32-S3-DevKitC
        run: bash prepare_image.sh "esp32-s3-devkitc-1" && cp build/*.zip release
      - name: Build Arduino Nano ESP32
        run: bash prepare_image.sh "arduino_nano_esp32" && cp build/*.zip release
      - name: Build LilyGo T-Embed CC1101
        run: bash prepare_image.sh "lilygo_t_embed_cc1101" && cp build/*.zip release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: release/*
